### PR TITLE
Fixed problem with `get_chat_id` when a edited message command is send

### PR DESCRIPTION
**Pull request by patrickpichler**
This is my very first pull request and i'm new to elixir, so if there is any problem on how i created the pull request or fixed problem please let me know! :)

### CODE REVIEW

**Comment by patrickpichler** [comment]
I noticed that my pull request is not working as expected.

**Comment by lubien** [comment]
Oh you fixed #4 , thanks!

Can I ask you to redo both commits in only one?

**Comment by patrickpichler** [comment]
So it is one commit now :)

**Comment by lubien** [comment]
Perfect

image

**Comment by lubien** [comment]
Also @patrickpichler I'll be releasing a new version of this anytime soon.

This time not a boilerplate but a library. With more helper macros too. Stay tuned.

**Pull request merged**
