### PR TITLE
Add routing

### PR DESCRIPTION
**Pull request by lubien**
* Router module with matcher macros
* Commander module with [Nadia] sender macros
* You may define command handlers in other modules

### CODE REVIEW

**Comment by lubien** [comment]
Can you take a look on this @Vizakenjack and say if it's what you need or if you have any ideas.

**Comment by lubien** [comment]
References #1

**Comment by vizakenjack** [comment]
Yes, that would be good. Also, you have a lot of macros wrapping Nadia's methods, maybe it would be better to create your own telegram api client? I don't like Nadia because it's not production-ready and I have to write some features. Your boilerplate is much better because it has almost everything to create a basic telegram bot.

**Comment by lubien** [comment]
It doesn't sound bad. Also can you point these features you have to write on your own? I'm going to merge this, create a new issue about them

**Comment by vizakenjack** [comment]
I need these features:
1. Params for commands
2. Make '/' optional and make any text be a possible command.
3. Move "update" variable to access it not only in 'command' block

About #1 and #2, the perfect way would be something like: 
```
command '/name' do
   #... shows current name ...
end

# if you want to change name via /name <nickname>
command '/name', params: [:new_name] do
  # ... changing name to a new_name
end

command '/give', params: [:username, :amount] do
  # ...giving username something
end
```

There should be any amount of params. If there is only one param, it should not be splitted, so if I write: `/name Harry Potter` it should set :new_name to "Harry Potter".

**Comment by vizakenjack** [comment]
Also, it would be useful to have something like BotFather's feature when it awaits for your answer.

So, instead of `/name <nickname>` it would be good to ask user to type nickname and catch it in a callback.

**Pull request merged**
